id = "discord"
name = "Discord"
version = "0.3.0"
schema_version = 1
authors = ["Valentine Briese <valentinegb@icloud.com>"]
description = "Discord integration."
repository = "https://github.com/valentinegb/zed-discord"

[language_servers.discord-ls]
name = "Discord LS"
languages = ["TOML", "Rust", "Nix", "JSON", "JSONC"]
